import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import "primereact/resources/themes/lara-dark-green/theme.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <PrimeReactProvider>
          <Navbar />
          <main className="min-h-[calc(100vh-80px)]">{children}</main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
